export const termsAndConditions = [
  {
    id: 1,
    title_ka: 'Eligibility and Registration',
    title_en: 'Eligibility and Registration',
    points_ka: [
      'Participation is open to students currently enrolled from the 9th grade',
      'A completed application form and payment are required to confirm enrollment',
      'Max. 50 students are accepted during one course',
      'Enrollment is subject to availability, according to the number of students',
    ],
    points_en: [
      'Participation is open to students currently enrolled from the 9th grade',
      'A completed application form and payment are required to confirm enrollment',
      'Max. 50 students are accepted during one course',
      'Enrollment is subject to availability, according to the number of students',
    ],
    is_required: false,
    key: 'eligibility_and_registration',
  },
  {
    id: 2,
    title_ka: 'Health and Safety',
    title_en: 'Health and Safety',
    points_ka: [
      'All participants must have a completed health form',
      'Parents/guardians are responsible for disclosing any medical conditions or allergies',
      'Adequate supervision and safety measures will be in place during all activities',
      'Academy staff are authorised to administer first aid and seek medical attention in emergencies',
    ],
    points_en: [
      'All participants must have a completed health form',
      'Parents/guardians are responsible for disclosing any medical conditions or allergies',
      'Adequate supervision and safety measures will be in place during all activities',
      'Academy staff are authorised to administer first aid and seek medical attention in emergencies',
    ],
    is_required: false,
    key: 'health_and_safety',
  },
  {
    id: 3,
    title_ka: 'Behaviour and Discipline',
    title_en: 'Behaviour and Discipline',
    points_ka: [
      'Students are expected to adhere to the Academy’s code of conduct at all times',
      'The use of alcohol, cigarettes, or any illegal substances is strictly prohibited',
      'Any behaviour deemed inappropriate may result in disciplinary action, including dismissal from the Academy without a refund',
      'Any student found in possession of or using these items will be dismissed from the Academy',
    ],
    points_en: [
      'Students are expected to adhere to the Academy’s code of conduct at all times',
      'The use of alcohol, cigarettes, or any illegal substances is strictly prohibited',
      'Any behaviour deemed inappropriate may result in disciplinary action, including dismissal from the Academy without a refund',
      'Any student found in possession of or using these items will be dismissed from the Academy',
    ],
    is_required: false,
    key: 'behaviour_and_discipline',
  },
  {
    id: 4,
    title_ka: 'Media Release',
    title_en: 'Media Release',
    points_ka: [
      'During all periods, photographs and videos will be taken for promotional purposes and public use',
    ],
    points_en: [
      'During all periods, photographs and videos will be taken for promotional purposes and public use',
    ],
    options_ka: [
      'I confirm that I have given prior consent for my child’s photos to be taken',
      'I refuse to give prior permission to use my child’s photos',
    ],
    options_en: [
      'I confirm that I have given prior consent for my child’s photos to be taken',
      'I refuse to give prior permission to use my child’s photos',
    ],
    is_required: true,
    key: 'media_release',
  },
  {
    id: 5,
    title_ka: 'Parent Involvement',
    title_en: 'Parent Involvement',
    points_ka: [
      'Parents/guardians are not permitted in the Academy area during activities, to ensure a focused environment for students',
      'Enquiries or concerns should be directed to Academy staff through the designated communication channels',
    ],
    points_en: [
      'Parents/guardians are not permitted in the Academy area during activities, to ensure a focused environment for students',
      'Enquiries or concerns should be directed to Academy staff through the designated communication channels',
    ],
    is_required: false,
    key: 'parent_involvement',
  },
  {
    id: 6,
    title_ka: 'Fees and Payment',
    title_en: 'Fees and Payment',
    points_ka: [
      'Fees must be paid in full at the time of registration unless prior arrangements have been made',
      'Fees are non-refundable except in cases of medical documentation or course cancellation',
      'Payment methods include credit/debit cards or bank transfers',
    ],
    points_en: [
      'Fees must be paid in full at the time of registration unless prior arrangements have been made',
      'Fees are non-refundable except in cases of medical documentation or course cancellation',
      'Payment methods include credit/debit cards or bank transfers',
    ],
    is_required: true,
    key: 'fees_and_payment',
  },
  {
    id: 7,
    title_ka: 'Cancellation & Refund Policy',
    title_en: 'Cancellation & Refund Policy',
    points_ka: [
      'Applicants may cancel their registration within 72 hours of signing up to receive a full refund',
      'Participants may request a date change if they provide valid medical documentation',
      'Cancellations made after the 72-hour window are non-refundable',
      'Participants who fail to attend without prior notice are not eligible for refunds or rescheduling',
      'If the camp must cancel a lecture due to unforeseen circumstances, participants will receive either a rescheduled session or a full refund',
      'Approved refunds will be processed within 7–10 business days via the original payment method',
    ],
    points_en: [
      'Applicants may cancel their registration within 72 hours of signing up to receive a full refund',
      'Participants may request a date change if they provide valid medical documentation',
      'Cancellations made after the 72-hour window are non-refundable',
      'Participants who fail to attend without prior notice are not eligible for refunds or rescheduling',
      'If the camp must cancel a lecture due to unforeseen circumstances, participants will receive either a rescheduled session or a full refund',
      'Approved refunds will be processed within 7–10 business days via the original payment method',
    ],
    is_required: true,
    key: 'cancellation_refund_policy',
  },
  {
    id: 8,
    title_ka: 'Application Review Process',
    title_en: 'Application Review Process',
    points_ka: [
      "Submitting an application does not guarantee admission. All applications are reviewed by the academy's organisational team.",
      'Final confirmation of acceptance will be sent via email after evaluating the applicant’s academic performance and other relevant criteria.',
      'Applicants with security-related concerns will not be accepted. The final admission list is confirmed in coordination with the security team.',
    ],
    points_en: [
      "Submitting an application does not guarantee admission. All applications are reviewed by the academy's organisational team.",
      'Final confirmation of acceptance will be sent via email after evaluating the applicant’s academic performance and other relevant criteria.',
      'Applicants with security-related concerns will not be accepted. The final admission list is confirmed in coordination with the security team.',
    ],
    is_required: false,
    key: 'application_review_process',
  },
];
