/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign un */
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generates new access token */
        post: operations["AuthController_generateAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ADMIN Sign in */
        post: operations["AdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generates new access token */
        post: operations["AdminController_findAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files/upload/{folder_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload files */
        post: operations["FilesController_uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files/upload/by-folder/{folder_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload files */
        post: operations["FilesController_uploadFilesByFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** remove files */
        delete: operations["FilesController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files/create-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create folder */
        post: operations["FilesController_createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files/update-folder/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update folder */
        patch: operations["FilesController_updateFolder"];
        trace?: never;
    };
    "/api/v1/admin/files/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all folders */
        get: operations["FilesController_getAllFolders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all files for admin */
        get: operations["FilesController_getAllfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create course */
        post: operations["CoursesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edit course */
        get: operations["CoursesController_findOne"];
        put?: never;
        post?: never;
        /** Delete course */
        delete: operations["CoursesController_remove"];
        options?: never;
        head?: never;
        /** Edit course */
        patch: operations["CoursesController_update"];
        trace?: never;
    };
    "/api/v1/admin/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update application status */
        patch: operations["ApplicationsController_update"];
        trace?: never;
    };
    "/api/v1/admin/applications/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** fetches all applications for a course */
        get: operations["ApplicationsController_getAllWithCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** fetches all applications for a course */
        get: operations["ApplicationsController_getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/campus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all campuses
         * @description Get all campuses
         */
        get: operations["CampusController_findAll"];
        put?: never;
        /**
         * Create a new campus
         * @description Create
         */
        post: operations["CampusController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/campus/{campus_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CampusController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/campus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a campus
         * @description Delete a campus
         */
        delete: operations["CampusController_remove"];
        options?: never;
        head?: never;
        patch: operations["CampusController_update"];
        trace?: never;
    };
    "/api/v1/admin/lecturer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LecturerController_findAll"];
        put?: never;
        post: operations["LecturerController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/lecturer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LecturerController_findOne"];
        put?: never;
        post?: never;
        delete: operations["LecturerController_remove"];
        options?: never;
        head?: never;
        patch: operations["LecturerController_update"];
        trace?: never;
    };
    "/api/v1/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApplicationController_findAll"];
        put?: never;
        /** Create application */
        post: operations["ApplicationController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/application/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApplicationController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ApplicationController_remove"];
        options?: never;
        head?: never;
        patch: operations["ApplicationController_update"];
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all courses */
        get: operations["CoursesController_findAllCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course by id */
        get: operations["CoursesController_findOneCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /** @description The email of the user */
            email: string;
            /** @description The password of the user */
            password: string;
        };
        CreateAuthDto: {
            /** @description The email of the user */
            email: string;
            /** @description The password of the user */
            password: string;
        };
        UserDto: {
            /** @description The id of the user */
            id: string;
            /** @description The email of the user */
            email: string;
        };
        AuthRtDto: {
            /** @description The user */
            user: components["schemas"]["UserDto"];
            /** @description access token */
            accessToken: string;
            /** @description refresh token */
            refreshToken: string;
        };
        SignInDto: {
            /** @description The email of the user */
            email: string;
            /** @description The password of the user */
            password: string;
        };
        GenerateNewAccessTokenDto: {
            /** @description The refresh token of the user */
            refreshToken: string;
        };
        AdminSignInDto: {
            /**
             * @description The username of the admin
             * @example admin
             */
            username: string;
            /**
             * @description The password of the admin
             * @example password
             */
            password: string;
        };
        AdminAuthRt: {
            /**
             * @description The username of the admin
             * @example admin
             */
            username: string;
            /**
             * @description The accessToken of the admin
             * @example accessToken
             */
            accessToken: string;
            /**
             * @description The refreshToken of the admin
             * @example admin
             */
            refreshToken: string;
        };
        GenerateNewAdminAccessTokenDto: {
            /** @description The refresh token of the user */
            refreshToken: string;
        };
        AdminDto: {
            /**
             * @description The username of the admin
             * @example admin
             */
            username: string;
        };
        UploadedFilesDto: {
            /**
             * @description The original name of the file
             * @example original_name
             */
            original_name: string;
            /**
             * @description The url of the file
             * @example url
             */
            url: string;
            /**
             * @description The type of the file
             * @example type
             */
            type: string;
            /**
             * @description The type of the file
             * @example locaiton
             */
            location: string;
        };
        NewUploadedFiles: {
            name: string;
            type: string;
        };
        FolderDto: {
            /** @description Folder name */
            folder_id: string;
            /** @description Folder name */
            folder_name: string;
            /** @description Folder name */
            created_at: string;
            /** @description Folder name */
            updated_at: string;
        };
        FileDto: {
            /**
             * @description Unique identifier for the media
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            media_id: string;
            /**
             * @description URL where the media is stored
             * @example https://example.com/media.jpg
             */
            media_url: string;
            /**
             * @description Name of the media file
             * @example image.jpg
             */
            media_name: string;
            /**
             * @description Location of the media
             * @example New York
             */
            location: string;
            /**
             * @description Type of the media
             * @example image
             */
            type: string;
            /**
             * @description Size of the media file
             * @default 0
             * @example 123.45
             */
            media_size: number;
            /**
             * @description Creation date of the media
             * @default now
             * @example 2025-02-24T00:00:00.000Z
             */
            created_at: string;
            /**
             * @description Last updated date of the media
             * @default updatedAt
             * @example 2025-02-24T00:00:00.000Z
             */
            updated_at: string;
            /**
             * @description Folder ID the media belongs to
             * @example abc123
             */
            folder_id?: string;
            /** @description Related folder information */
            folder?: components["schemas"]["FolderDto"];
        };
        CreateFolderDto: {
            /** @description Folder name */
            folder_name: string;
        };
        FileDtoRt: {
            /** @description List of files */
            data: components["schemas"]["FileDto"][];
            /** @description Total number of files */
            count: number;
        };
        CreateCourseDto: {
            /** @description Title in Georgian */
            title_ka: string;
            /** @description Title in English */
            title_en: string;
            /** @description Description in Georgian */
            description_ka: string;
            /** @description Description in English */
            description_en: string;
            /** @description Start date of the course */
            start_date: string;
            /** @description End date of the course */
            end_date: string;
            /**
             * @description Maximum number of students
             * @default 50
             */
            max_students: number;
            /**
             * @description Price of the course
             * @default 0
             */
            price: number;
            /** @description Lecturer ID */
            lecturer_id?: string;
            /** @description List of lecturer IDs */
            lecturers?: string[];
            /** @description List of category IDs */
            campus_id?: string;
            /** @description Course media */
            course_media?: components["schemas"]["FileDto"][];
            /** @description Course files */
            course_files?: components["schemas"]["FileDto"][];
            /** @description kewords ka */
            keywords_ka?: string;
            /** @description kewords ka */
            keywords_en?: string;
            /** @description kewords ka */
            short_des_en?: string;
            /** @description kewords ka */
            short_des_ka?: string;
        };
        ApplicationsCount: {
            /** @description Number of applications for the course */
            application: number;
        };
        FileCourseAssnDto: {
            media_course_assn_id: string;
            media_id: string;
            course_id: string;
            media?: components["schemas"]["FileDto"];
        };
        LecturerDto: {
            id: string;
            picture?: string;
            first_name_ka: string;
            last_name_ka: string;
            first_name_en: string;
            last_name_en: string;
            biography_ka: string;
            biography_en: string;
            created_at: string;
            updated_at: string;
        };
        LecturerCourseAssnDto: {
            lecturer: components["schemas"]["LecturerDto"];
        };
        CampusFileAssnDto: {
            campus_media_assn_id: string;
            media_id: string;
            campus_id: string;
            media?: components["schemas"]["FileDto"];
        };
        CampusDto: {
            campus_id: string;
            campus_name_ka: string;
            campus_name_en: string;
            maps_url?: string;
            description_ka: string;
            description_en: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            campus_media_assn: components["schemas"]["CampusFileAssnDto"][];
            campus_file_assn: components["schemas"]["CampusFileAssnDto"][];
        };
        CourseDto: {
            /**
             * Format: uuid
             * @description Unique ID of the course
             */
            course_id: string;
            /** @description Title in Georgian */
            title_ka: string;
            /** @description Title in English */
            title_en: string;
            /** @description Description in Georgian */
            description_ka: string;
            /** @description Description in English */
            description_en: string;
            /**
             * Format: date-time
             * @description Start date of the course
             */
            start_date: string;
            /**
             * Format: date-time
             * @description End date of the course
             */
            end_date: string;
            /**
             * @description Maximum number of students
             * @default 50
             */
            max_students: number;
            /**
             * @description Price of the course
             * @default 0
             */
            price: number;
            /**
             * Format: uuid
             * @description ID of the lecturer
             */
            lecturer_id?: string;
            /**
             * Format: uuid
             * @description ID of the creator
             */
            created_by?: string;
            /**
             * Format: date-time
             * @description Date the course was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Date the course was last updated
             */
            updated_at: string;
            /** @description Apps count */
            _count?: components["schemas"]["ApplicationsCount"];
            /** @description Array of media associated with the course */
            media_course_assn: components["schemas"]["FileCourseAssnDto"][];
            /** @description Array of media associated with the course */
            files_course_assn: components["schemas"]["FileCourseAssnDto"][];
            /** @description kewords ka */
            keywords_ka?: string;
            /** @description kewords ka */
            keywords_en?: string;
            /** @description kewords ka */
            short_des_en?: string;
            /** @description kewords ka */
            short_des_ka?: string;
            /** @description Array of media associated with the course */
            lecturer_course_assn: components["schemas"]["LecturerCourseAssnDto"][];
            /** @description Array of media associated with the course */
            campuse: components["schemas"]["CampusDto"];
        };
        EditCourseDto: {
            /** @description Title in Georgian */
            title_ka?: string;
            /** @description Title in English */
            title_en?: string;
            /** @description Description in Georgian */
            description_ka?: string;
            /** @description Description in English */
            description_en?: string;
            /** @description Start date of the course */
            start_date?: string;
            /** @description End date of the course */
            end_date?: string;
            /**
             * @description Maximum number of students
             * @default 50
             */
            max_students: number;
            /**
             * @description Price of the course
             * @default 0
             */
            price: number;
            /** @description Lecturer ID */
            lecturer_id?: string;
            /** @description Course media */
            course_media?: components["schemas"]["FileDto"][];
            /** @description Course files */
            course_files?: components["schemas"]["FileDto"][];
            /** @description kewords ka */
            keywords_ka?: string;
            /** @description kewords ka */
            keywords_en?: string;
            /** @description kewords ka */
            short_des_en?: string;
            /** @description kewords ka */
            short_des_ka?: string;
            /** @description List of lecturer IDs */
            lecturers?: string[];
            /** @description List of category IDs */
            campus_id?: string;
        };
        UpdateApplicationDtoAdmin: {
            status: string;
        };
        ApplicationDto: {
            /**
             * Format: uuid
             * @description Unique application ID
             */
            application_id: string;
            /** @description Course ID */
            course_id: string;
            /**
             * @description Application status
             * @default pending
             */
            status: string;
            /** @description Parent first name */
            parent_name: string;
            /** @description Parent last name */
            parent_lastname: string;
            /** @description Parent personal number */
            parent_pn: string;
            /** @description Parent email */
            parent_email: string;
            /** @description Parent phone number */
            parent_phone: string;
            /**
             * @description Relation to the child
             * @default parent
             */
            relation: string;
            /** @description Child first name */
            child_name: string;
            /** @description Child last name */
            child_lastname: string;
            /** @description Child email */
            child_email?: string;
            /** @description Child date of birth */
            child_dob: string;
            /** @description Child date of birth */
            created_at: string;
            /** @description Child date of birth */
            updated_at: string;
            /** @description Course */
            course?: components["schemas"]["CourseDto"];
        };
        CreateCampusDto: {
            /** @description Title in Georgian */
            campus_name_ka: string;
            /** @description Title in English */
            campus_name_en: string;
            /** @description Description in Georgian */
            description_ka: string;
            /** @description Description in English */
            description_en: string;
            /** @description Start date of the course */
            maps_url: string;
            /** @description Course media */
            campus_media?: components["schemas"]["FileDto"][];
            /** @description Course files */
            campus_files?: components["schemas"]["FileDto"][];
        };
        CreateLecturerDto: {
            /** @description Profile picture URL */
            picture?: string;
            /** @description First name in Georgian */
            first_name_ka: string;
            /** @description Last name in Georgian */
            last_name_ka: string;
            /** @description First name in English */
            first_name_en: string;
            /** @description Last name in English */
            last_name_en: string;
            /** @description Biography in Georgian */
            biography_ka: string;
            /** @description Biography in English */
            biography_en: string;
        };
        CreateApplicationDto: {
            /**
             * Format: uuid
             * @description Unique identifier for the course
             */
            course_id: string;
            /** @description Parent's first name */
            parent_name: string;
            /** @description Parent's last name */
            parent_lastname: string;
            /** @description Parent's personal number */
            parent_pn: string;
            /**
             * Format: email
             * @description Parent's email address
             */
            parent_email: string;
            /** @description Parent's phone number */
            parent_phone: string;
            /**
             * @description Relation to the child
             * @default parent
             */
            relation: string;
            /** @description Child's first name */
            child_name: string;
            /** @description Child's last name */
            child_lastname: string;
            /**
             * Format: email
             * @description Child's email address
             */
            child_email?: string;
            /** @description Child's date of birth */
            child_dob: string;
        };
        UpdateApplicationDto: {
            /**
             * Format: uuid
             * @description Unique identifier for the course
             */
            course_id?: string;
            /** @description Parent's first name */
            parent_name?: string;
            /** @description Parent's last name */
            parent_lastname?: string;
            /** @description Parent's personal number */
            parent_pn?: string;
            /**
             * Format: email
             * @description Parent's email address
             */
            parent_email?: string;
            /** @description Parent's phone number */
            parent_phone?: string;
            /**
             * @description Relation to the child
             * @default parent
             */
            relation: string;
            /** @description Child's first name */
            child_name?: string;
            /** @description Child's last name */
            child_lastname?: string;
            /**
             * Format: email
             * @description Child's email address
             */
            child_email?: string;
            /** @description Child's date of birth */
            child_dob?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuthDto"];
            };
        };
        responses: {
            /** @description User successfully registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRtDto"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            /** @description User successfully signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRtDto"];
                };
            };
        };
    };
    AuthController_generateAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateNewAccessTokenDto"];
            };
        };
        responses: {
            /** @description User token successfully refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRtDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSignInDto"];
            };
        };
        responses: {
            /** @description Admin successfully signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthRt"];
                };
            };
        };
    };
    AdminController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateNewAdminAccessTokenDto"];
            };
        };
        responses: {
            /** @description Admin token successfully refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthRt"];
                };
            };
        };
    };
    AdminController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin successfully signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDto"];
                };
            };
        };
    };
    FilesController_uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder name to upload files */
                folder_name: string;
            };
            cookie?: never;
        };
        /** @description List of files to upload */
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"];
            };
        };
        responses: {
            /** @description Files successfully uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedFilesDto"][];
                };
            };
        };
    };
    FilesController_uploadFilesByFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder name to upload files */
                folder_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUploadedFiles"][];
            };
        };
        responses: {
            /** @description Files successfully uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDto"][];
                };
            };
        };
    };
    FilesController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description file name to delete */
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files successfully removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderDto"];
            };
        };
        responses: {
            /** @description Folder successfully created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"];
                };
            };
        };
    };
    FilesController_updateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Folder id to update */
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderDto"];
            };
        };
        responses: {
            /** @description Folder successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"];
                };
            };
        };
    };
    FilesController_getAllFolders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All folders successfully fetched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"][];
                };
            };
        };
    };
    FilesController_getAllfiles: {
        parameters: {
            query: {
                /** @description Number of rows per page */
                rowsPerPage: number;
                /** @description Current page number */
                page: number;
                /** @description Text to search for */
                searchText?: string;
                /** @description Field to sort by */
                sortBy: string;
                /** @description Direction of sorting */
                direction: string;
                /** @description folder name */
                folder_name?: string;
                /** @description folder name */
                file_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All folders successfully fetched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDtoRt"];
                };
            };
        };
    };
    CoursesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseDto"];
            };
        };
        responses: {
            /** @description Course successfully created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"];
                };
            };
        };
    };
    CoursesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"];
                };
            };
        };
    };
    CoursesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoursesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCourseDto"];
            };
        };
        responses: {
            /** @description Course successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"];
                };
            };
        };
    };
    ApplicationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationDtoAdmin"];
            };
        };
        responses: {
            /** @description Application updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_getAllWithCourse: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string;
            };
            header?: never;
            path: {
                /** @description Course id */
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description all applicants on course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDto"][];
                };
            };
        };
    };
    ApplicationsController_getAll: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description all applicants on course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDto"][];
                };
            };
        };
    };
    CampusController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campuses fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"][];
                };
            };
        };
    };
    CampusController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusDto"];
            };
        };
        responses: {
            /** @description Campus created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"];
                };
            };
        };
    };
    CampusController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campus name */
                campus_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campus fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusDto"];
                };
            };
        };
    };
    CampusController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campus deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampusController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campus ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LecturerController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturer created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerDto"][];
                };
            };
        };
    };
    LecturerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLecturerDto"];
            };
        };
        responses: {
            /** @description Lecturer created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerDto"];
                };
            };
        };
    };
    LecturerController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lecturer id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturer created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerDto"];
                };
            };
        };
    };
    LecturerController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LecturerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lecturer id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLecturerDto"];
            };
        };
        responses: {
            /** @description Lecturer created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LecturerDto"];
                };
            };
        };
    };
    ApplicationController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationDto"];
            };
        };
        responses: {
            /** @description Application successfully created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoursesController_findAllCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"][];
                };
            };
        };
    };
    CoursesController_findOneCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDto"];
                };
            };
        };
    };
}
